/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.login;

import java.sql.Connection;
import javax.swing.DefaultListModel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author hammad
 */
public class prefrence extends javax.swing.JFrame {
    Connection conn;
    int user_Id=0;
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement pstmt = null;
    personaldetails pd = new personaldetails();
    
    private prefrence() {
        initComponents();
        conn=ConnectionDB.getConnection();
        getReligions(conn);

    }
    
    public prefrence(Connection conn, int userID){
        initComponents();
        this.conn = conn;
        this.user_Id = userID;
        getReligions(conn);
        txt_id.setText(String.valueOf(user_Id));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        min_age = new javax.swing.JTextField();
        max_height = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_income = new javax.swing.JTextField();
        cb_religion = new javax.swing.JComboBox<>();
        cb_sect = new javax.swing.JComboBox<>();
        cb_lang = new javax.swing.JComboBox<>();
        cb_level = new javax.swing.JComboBox<>();
        cb_occ = new javax.swing.JComboBox<>();
        cb_smoking = new javax.swing.JComboBox<>();
        cb_drinking = new javax.swing.JComboBox<>();
        cb_fam = new javax.swing.JComboBox<>();
        cb_marital = new javax.swing.JComboBox<>();
        cb_child = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        max_age = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        min_height = new javax.swing.JTextField();
        txt_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tell Us About Your Partner");

        jLabel2.setText("min age");

        jLabel3.setText("max age");

        jLabel4.setText("religion");

        jLabel5.setText("sect");

        jLabel6.setText("preferred language");

        jButton1.setText("next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("education level");

        jLabel8.setText("occupation");

        jLabel9.setText("Average Income");

        jLabel10.setText("Smoking");

        jLabel11.setText("Drinking");

        jLabel12.setText("Desired family");

        jLabel13.setText("Martial status");

        jLabel14.setText("Children");

        cb_religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_religionActionPerformed(evt);
            }
        });

        cb_sect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_lang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urdu" }));

        cb_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matric", "O Levels", "A Levels", "Intermediate", "Undegrad", "PHD", "Any" }));

        cb_occ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UnEmployeed", "Business Person", "Corporate Employee", "Teacher", "Any" }));

        cb_smoking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Full-Time", "Ocassional", "Doesn't Matter" }));
        cb_smoking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_smokingActionPerformed(evt);
            }
        });

        cb_drinking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Full-Time", "Ocassional", "Doesn't Matter" }));
        cb_drinking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_drinkingActionPerformed(evt);
            }
        });

        cb_fam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Joint", "Any" }));
        cb_fam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_famActionPerformed(evt);
            }
        });

        cb_marital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Never-Married", "Divorced", "Any", " ", " " }));
        cb_marital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_maritalActionPerformed(evt);
            }
        });

        cb_child.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", "Doesn't Matter" }));
        cb_child.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_childActionPerformed(evt);
            }
        });

        jLabel15.setText("max height");

        jLabel16.setText("min height");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(42, 42, 42)))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(max_height)
                                    .addComponent(min_age)
                                    .addComponent(cb_religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_sect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_lang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_occ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(max_age)
                                    .addComponent(min_height))
                                .addGap(172, 172, 172)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel10)))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_income, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_smoking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_drinking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_fam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_marital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_child, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cb_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel1)
                        .addGap(243, 243, 243)
                        .addComponent(txt_id)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(256, 256, 256))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(cb_smoking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(cb_drinking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cb_fam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cb_marital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(max_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cb_child, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_id))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(min_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(max_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(min_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cb_religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_sect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cb_lang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_occ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
     public void getReligions(Connection conn){
        
        try {
            stmt = conn.createStatement();
            String query = "SELECT religion_name FROM vw_religion";
            rs = stmt.executeQuery(query);

    // Create a list to store the country names
            java.util.List<String> religionList = new ArrayList<>();

    // Iterate over the result set and add country names to the list
            while (rs.next()) {
            String religionName = rs.getString("religion_name");
            religionList.add(religionName);
            }

    // Convert the list to an array for populating the JComboBox
            String[] religions = religionList.toArray(new String[0]);
            
            // Assuming you have a JComboBox named "countryComboBox"
            cb_religion.setModel(new DefaultComboBoxModel<>(religions));

    // Now you have the countries array to populate the JComboBox
    // ...
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
    // Close the ResultSet, Statement, and Connection
        if (rs != null) {
            try {
                rs.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        if (stmt != null) {
            try {
                stmt.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        }
    }
    
    public void getSects(Connection conn, String selectedReligion) {
    try {
        String query = "SELECT sect_name FROM vw_sect WHERE religion_name = ?";
        pstmt = conn.prepareStatement(query);
        pstmt.setString(1, selectedReligion);
        rs = pstmt.executeQuery();

        java.util.List<String> sectList = new ArrayList<>();
        while (rs.next()) {
            String sectName = rs.getString("sect_name");
            sectList.add(sectName);
        }

        String[] sects = sectList.toArray(new String[0]);
        cb_sect.setModel(new DefaultComboBoxModel<>(sects));
    } catch (SQLException e) {
        e.printStackTrace();
    } finally {
        if (rs != null) {
            try {
                rs.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        if (pstmt != null) {
            try {
                pstmt.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
    
    public void insertPartnerPreferences(Connection conn, int userId) {
        try {
            String query = "{CALL sp_InsertPartnerPreferences(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}";
            pstmt = conn.prepareCall(query);
            pstmt.setInt(1, userId);
            pstmt.setInt(2, Integer.parseInt(min_age.getText()));
            pstmt.setInt(3, Integer.parseInt(max_age.getText()));
            pstmt.setDouble(4, Double.parseDouble(min_height.getText()));
            pstmt.setDouble(5, Double.parseDouble(max_height.getText()));
            pstmt.setString(6, (String) cb_religion.getSelectedItem());
            pstmt.setString(7, (String) cb_sect.getSelectedItem());
            pstmt.setString(8, (String) cb_lang.getSelectedItem());
            pstmt.setString(9, (String) cb_level.getSelectedItem());
            pstmt.setString(10,(String) cb_occ.getSelectedItem());
            pstmt.setDouble(11, Double.parseDouble(txt_income.getText()));
            pstmt.setString(12, (String) cb_smoking.getSelectedItem());
            pstmt.setString(13, (String) cb_drinking.getSelectedItem());
            pstmt.setString(14, (String) cb_fam.getSelectedItem());
            pstmt.setString(15, (String) cb_marital.getSelectedItem());
            pstmt.setString(16, (String) cb_child.getSelectedItem());

            pstmt.executeUpdate();
            System.out.println("Partner preferences inserted successfully.");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Invalid Details", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(!min_age.getText().isBlank()){
           insertPartnerPreferences(conn, 16);
            new SignUp(conn,user_Id).setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Fill all the details plese", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_smokingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_smokingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_smokingActionPerformed

    private void cb_drinkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_drinkingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_drinkingActionPerformed

    private void cb_famActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_famActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_famActionPerformed

    private void cb_maritalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_maritalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_maritalActionPerformed

    private void cb_childActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_childActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_childActionPerformed

    private void cb_religionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_religionActionPerformed
        // TODO add your handling code here:
        String selectedReligion = (String) cb_religion.getSelectedItem();
        getSects(conn, selectedReligion);
    }//GEN-LAST:event_cb_religionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prefrence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prefrence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prefrence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prefrence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prefrence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_child;
    private javax.swing.JComboBox<String> cb_drinking;
    private javax.swing.JComboBox<String> cb_fam;
    private javax.swing.JComboBox<String> cb_lang;
    private javax.swing.JComboBox<String> cb_level;
    private javax.swing.JComboBox<String> cb_marital;
    private javax.swing.JComboBox<String> cb_occ;
    private javax.swing.JComboBox<String> cb_religion;
    private javax.swing.JComboBox<String> cb_sect;
    private javax.swing.JComboBox<String> cb_smoking;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField max_age;
    private javax.swing.JTextField max_height;
    private javax.swing.JTextField min_age;
    private javax.swing.JTextField min_height;
    private javax.swing.JLabel txt_id;
    private javax.swing.JTextField txt_income;
    // End of variables declaration//GEN-END:variables
}
